export const photographers = [
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
];

export const major = [
    "Wedding",
    "Portrait",
    "Landscape",
    "Fashion",
    "Sports",
    "Wildlife",
    "Event",
    "Commercial",
    "Travel",
    "Documentary",
];

export const photos = [
    {
        src: "a.webp",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
];
