export const photographers = [
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
];
