export const photographers = [
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
];

export const major = [
    "Wedding",
    "Portrait",
    "Landscape",
    "Fashion",
    "Sports",
    "Wildlife",
    "Event",
    "Commercial",
    "Travel",
    "Documentary",
];

export const photos = [
    {
        src: "a.webp",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: [],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "e.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "f.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "a.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "c.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "b.jpg",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
    {
        src: "d.webp",
        bookmark: ["green", "red"],
        author: "dinhbang",
        likes: 12,
        comments: 54,
        saves: 12,
    },
];

export const photographerProfile = {
    img: "ava.jpg",
    name: "Photographer Daniele Torella",
    location: "Rome, Italy ",
    userName: "danieletorella",
    description:
        "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, Elle & Vanity Fair.",
    joiningAt: "15/3/2025",
    language: "italian, english, spanish",
    follower: 1113,
    phoneNumber: "0912341234",
    award: [
        "The best wedding photographer in the world",
        "Top 3 best couple photographers in the world",
    ],
    major: [
        { name: "weding", price: 1000000 },
        { name: "couples", price: 2000000 },
        { name: "materity", price: 30000000 },
        { name: "family", price: 4000000 },
    ],
    website: "bangdinh.com",
    price: [
        { name: "weding", price: 1000000 },
        { name: "couples", price: 2000000 },
        { name: "materity", price: 30000000 },
        { name: "family", price: 4000000 },
    ],
};
